In [1]:
import nbimporter
import classes as cl

In [2]:
import numpy as np

In [3]:
tests = {}

# Strategies

## clockwise_escape()

In [4]:
# 0 1 2
# 7   3
# 6 5 4
foxes_around = [0, 0, 1, 1, 3, 1, 0, 0]
tests["clockwise_escape_0"] = ( raf.
    clockwise_escape(foxes_around , 7, False) == 7 )

foxes_around = [0, 0, 1, 1, 3, 1, 0, 0]
tests["clockwise_escape_1"] = ( raf.
    clockwise_escape(foxes_around , 5, False) == 0 )

foxes_around = [10, 0, 1, 1, 3, 1, 0, 2]
tests["clockwise_escape_2"] = ( raf.
    clockwise_escape(foxes_around , 5, False) == 1 )

foxes_around = [10, 0, 1, 1, 3, 1, 0, 2]
tests["clockwise_escape_2"] = ( raf.
    clockwise_escape(foxes_around , 5, False) == 1 )

false_keys = filter(lambda items: not items[1], tests.items())
print("Failed tests: ")
print([key for key, value in false_keys])

Failed tests: 
[]


## chasing_1()

In [5]:
# 0 1 2
# 7   3
# 6 5 4
rabbits_around = [0, 0, 2, 0, 0, 0, 0, 1]
chasing_1_1 = raf.chasing_1(rabbits_around, 0, True, False) == 3
tests["chasing_1_0"] = chasing_1_1

rabbits_around = [0, 0, 2, 0, 0, 0, 0, 1]
chasing_1_2 = raf.chasing_1(rabbits_around, 2, True, True) == 3
tests["chasing_1_1"] = chasing_1_2

rabbits_around = [0, 0, 0, 1, 0, 0, 0, 3]
chasing_1_3 = raf.chasing_1(rabbits_around, 5, False, True) == 5
tests["chasing_1_2"] = chasing_1_3

In [6]:
for key, value in tests.items():
    print(f"{key}: {value}")

clockwise_escape_0: True
clockwise_escape_1: True
clockwise_escape_2: True
chasing_1_0: True
chasing_1_1: True
chasing_1_2: True


# Grid

In [7]:
# [row, column, [rabbits, foxes]]
height = 3
width = 4

grid = np.zeros((height, width, 2), dtype=int)

# in grid[1,2]
rabbits = 5
foxes = 6

grid[1, 2, 0] = rabbits
grid[1, 2, 1] = foxes

# in grid[0,3]
rabbits = 7
foxes = 8
grid[0, 3, 0] = rabbits
grid[0, 3, 1] = foxes

grid

array([[[0, 0],
        [0, 0],
        [0, 0],
        [7, 8]],

       [[0, 0],
        [0, 0],
        [5, 6],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

## valid_position()

In [8]:
height = 3
width = 5
grid = np.zeros((height, width, 2), dtype=int)

raf.valid_position(0, 4, grid.shape)
tests["valid_postion_0"] = raf.valid_position(0, 4, grid.shape) == (0, 4)
tests["valid_postion_1"] = raf.valid_position(0, 5, grid.shape) == (0, 0)
tests["valid_postion_2"] = raf.valid_position(0, -1, grid.shape) == (0, 4)

tests["valid_postion_3"] = raf.valid_position(2, 0, grid.shape) == (2, 0)
tests["valid_postion_4"] = raf.valid_position(3, 0, grid.shape) == (0, 0)
tests["valid_postion_5"] = raf.valid_position(-1, 0, grid.shape) == (2, 0)

tests["valid_postion_6"] = raf.valid_position(2, 4, grid.shape) == (2, 4)
tests["valid_postion_7"] = raf.valid_position(3, 5, grid.shape) == (0, 0)
tests["valid_postion_8"] = raf.valid_position(-1, -1, grid.shape) == (2, 4)

false_keys = filter(lambda items: not items[1], tests.items())
print("Failed tests: ")
print([key for key, value in false_keys])


Failed tests: 
[]


## get_animals_around()

In [9]:
# [row, column, [rabbits, foxes]]
height = 3
width = 4

grid = np.zeros((height, width, 2), dtype=int)

c = 0
for row in range(height):
    for col in range(width):
        grid[row, col, 0] = c
        grid[row, col, 1] = c + 1
        c += 2
grid

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [10]:
# height = 3
# width = 4

# 0 1 2
# 7   3
# 6 5 4

# 0  2  4  6
# 8  10 12 14
# 16 18 20 22


tests["get_animals_around_0"] = (raf.get_animals_around(
    grid, 2, 3, "rabbits") == [12, 14, 8, 16, 0, 6, 4, 20] ).all()

tests["get_animals_around_1"] = (raf.get_animals_around(
    grid, 2, 3, "foxes") == [13, 15, 9, 17, 1, 7, 5, 21] ).all()

false_keys = filter(lambda items: not items[1], tests.items())
print("Failed tests: ")
print([key for key, value in false_keys])
# tests


Failed tests: 
[]


# Classes

## Map

In [4]:
m1 = cl.Map(3, 3)
m1.populate(10, "rabbit", "random")
m1.get_population_map()


array([[[0, 0],
        [2, 0],
        [3, 0]],

       [[0, 0],
        [1, 0],
        [1, 0]],

       [[0, 0],
        [2, 0],
        [1, 0]]])

In [ ]:
m1 = cl.Map(3, 3)
m1.populate(10, "rabbit", "random")
m1.reproduction("rabbit")
m1.get_population_map()

In [5]:
false_keys = filter(lambda items: not items[1], tests.items())
print("Failed tests: ")
print([key for key, value in false_keys])

Failed tests: 
[]
